### ISSUE TITLE
ttt2_lyc_regen_rate ConVar is Unimplemented

### ISSUE THREAD

**Issue by AaronMcKenney** [ZacharyHinds/ttt2-role-lyc#2]
**Version of Code:** Commit 7b94bb8
**Version of TTT2:** https://github.com/TTT-2/TTT2/pull/652 (Although it doesn't matter here)

**Description:** Simply put, ttt2_lyc_regen_rate is created but not utilized in the code base, as can be observed from this search link:
https://github.com/ZacharyHinds/ttt2-role-lyc/search?q=ttt2_lyc_regen_rate&type=
Based off the code base and convar description I think it's effectively 1 all the time.

**To Reproduce:** 
1. Become an Unleashed Lycanthrope.
2. Lower HP below maximum.
3. Modify ttt2_lyc_regen_rate convar to wild extremes.

...

I dunno if putting this up was super necessary given that this role was just made public today, but I felt I may as well point it out in some capacity.

**Comment by ZacharyHinds** [comment]
Thanks for that catch! Fixed in Commit cb5fdaf7c730a9e46fb85a3034a58e93be9fe8ec
